### ISSUE TITLE
TryParse throws exception if null is passed

### ISSUE THREAD

**Issue by gregmac** [jsakamoto/ipaddressrange#14]
I don't think TryParse should be throwing an exception for any type of input. It's currently limited to FormatException and I'm not sure why to not just catch any Exception and return false.

**Comment by jsakamoto** [comment]
>  I'm not sure why to not just catch any Exception and return false.

because, I'm afraid that I can't catch what bug in these codes.

If we catch all types of exception without thought, we could not know what's happen.

I had feeled that situation was foolish...

But,  exactly as you say, perhaps we should catch any exceptions to keep more safety.

Please let me few days to cosider well about your pull request.

**Comment by gregmac** [comment]
That's fair, though I'd say that there should be enough unit tests to be confident in knowing there are not any situations that throw an unexpected exception.

Either way, at the very least, this is a valid test case that should be added and the `TryParse` code should at least catch the `ArgumentNullException`.

----

For reference, [`bool.TryParse`](http://referencesource.microsoft.com/#mscorlib/system/boolean.cs,c8d4e2d26d59f9d0) handles things explicitly, and several other TryParse methods do the same. 

[`IPAddress.TryParse`](http://referencesource.microsoft.com/#System/net/System/Net/IPAddress.cs,f0ee31c1b5e0d5ed) calls an internal TryParse method that is a heap of ugliness, but does lots of this:
````csharp
  if (tryParse) {
    return null;
  }
  throw new ArgumentNullException("ipString");
````

**Comment by M-Zuber** [comment]
I agree with @gregmac (see #7).
In fact even though I made the PR for TryParse, I don't use it due to this issue.
