### ISSUE TITLE
Cannot parse ARIN IPv6 IP addresses

### ISSUE THREAD

**Issue by zmarty** [jsakamoto/ipaddressrange#18]
Unfortunately, the ARIN IP range database from https://www.arin.net/ contains somewhat invalid IPv6 addresses in almost all their IPv6 IP ranges.

Below are a few examples of individual IPv6 addresses. Each example below contains the start ip of an IP range:

    2001:49D0:140:
    2001:504:0:5:
    2001:4978:100:

The reason why these IP addresses are invalid is that they end in a colon instead of a double colon.

If you can change the library to handle this type of address as well I would appreciate it.

Thanks!

**Comment by jsakamoto** [comment]
Thank you for your message.

But I would like to do not any actions to this issue.

Because, you know, this is the ARIN IP range database's problem.

Sorry for your suggestion, I'm not going to accept invalid format. It doesn't responsibility of this library.

**Comment by zmarty** [comment]
I have also sent an e-mail to ARIN explaining the problem. But please be aware this library is being especially used to parse databases like ARIN, RIPE, etc. Sometimes the reality is different than the standard / protocol.

**Comment by jsakamoto** [comment]
I understand what you want to say, and your standing position.

> Sometimes the reality is different than the standard / protocol. 

I completely agree this point.

But, this library, like many people sharing and using, does not the layer to solve this issue.

To solve this issue, we should implement some codes at application layer, not these commonly libraries.
