### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by brooklynDev** [jsakamoto/ipaddressrange#25]
Thanks for a very useful library.

Any plans for adding .Net Core support? I went through the source code, and the only issue I see here is with regards to Serialization. Currently, this is not supported in .Net Core. See here:

https://github.com/dotnet/corefx/issues/6564

Thanks!

**Comment by jsakamoto** [comment]
Thank you for your post.

Yes, I hope, add .Net Core support, but I have no time in these days.

Please let me few weeks or months, or I always welcome pull request for .Net Core support :)

**Comment by jsakamoto** [comment]
@brooklynDev I released .NET Core supported edition beta release.

https://twitter.com/jsakamoto/status/803580198469779456

Would you like to try it?

**Comment by brooklynDev** [comment]
@jsakamoto Wow, thanks so much for the effort. Just tested it, and it all looks green. I'll close the issue, thanks again!
