### ISSUE TITLE
UWP /Winrt port

### ISSUE THREAD

**Issue by hannespreishuber** [jsakamoto/ipaddressrange#27]
tried to port your code to UWP (in Q&D)
missing SerializationInfo and further classes

**Comment by jsakamoto** [comment]
@hannespreishuber Thank you for your comment.

I'll try it, but i'm busy in these days, so please let me few weeks.

I'm reading this article now: https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages

**Comment by jsakamoto** [comment]
@hannespreishuber well, had you try IPAddressRange NuGet package v.1.6.2.1 Beta? 

https://www.nuget.org/packages/IPAddressRange/1.6.2.1-beta

(It is Beta release, so you should append "-pre" option for "Install-Package" command to install this version.)

**Comment by jsakamoto** [comment]
@hannespreishuber I tried it at commit 3d29e73 !

 Could you try IPAddressRange v.1.6.2.6-beta NuGet package?

https://www.nuget.org/packages/IPAddressRange/1.6.2.6-beta

**Comment by hannespreishuber** [comment]
HI
Package installation works in VS 2017 RC2, Windows 10 Anniversary 64Bit
great- thanks

**Comment by jsakamoto** [comment]
@hannespreishuber Thank you for your confirmation.

I'll release v.1.6.2 as officially in few days after.

**Comment by jsakamoto** [comment]
I already released v.1.6.2.

https://www.nuget.org/packages/IPAddressRange/1.6.2.7
