### ISSUE TITLE
Lots of dependencies

### ISSUE THREAD

**Issue by UweKeim** [jsakamoto/ipaddressrange#29]
Trying to NuGet your library into my .NET 4.6.2 project, there are tons of dependencies it tries to install:

![image](https://cloud.githubusercontent.com/assets/415439/26537736/0e3952b0-4442-11e7-8661-c2aedb646b1d.png)

Most likely this is because your project targets .NET Standard and it has to close the gaps from .NET 4.6.2 to .NET Standard.

Since your library effectively seems to consist of only two files (`Bits.cs` and `IPAddressRange.cs`) I feel that this is way too much for my project to justify adding so many dependencies.

**My question:**

Beside directly using the two sources files, is there any other NuGet solution to still get your library and benefit from updates, without adding all those dependencies?

**Comment by jsakamoto** [comment]
@UweKeim Thank you for your reporting!

I resolved this issue by [add one line](https://github.com/jsakamoto/ipaddressrange/commit/759aca00f28e3e03fb680a4e6dd15b8f378710d6#diff-83ed1ed9db7d7f67e1f392de6187be27R37) into package metadata about ".NET Framework 4.5 or above has no dependencies" explicitly.

Could you try to use v.2.0.0.3-Beta?

https://www.nuget.org/packages/IPAddressRange/2.0.0.3-beta

```shell
PM> Install-Package IPAddressRange -Pre
```

**Comment by UweKeim** [comment]
It works as expected. Thanks a lot for your fast and helpful fix 😄.
