### ISSUE TITLE
Add another kind of range, i.e. X.Y.Z.A-B

### ISSUE THREAD

**Issue by konrad-kruczynski** [jsakamoto/ipaddressrange#33]
Such range would effectively mean **X.Y.Z.A-X.Y.Z.B**.

What do you think?

**Comment by jsakamoto** [comment]
This short hand is fun! 👍 

However, implementing this syntax support may be not as simple as I thought.  
 (For example, how to treat "192.168.0.12-3.45"? It should be reject? or convert to 192.168.0.12 - 192.168.3.45? etc...)

Therefore I guess that implementation cost efficiency will be worse.

I will consider it if anyone send to me a pull request of this syntax support. 😄

**Comment by jsakamoto** [comment]
Thank you @konrad-kruczynski for you PR #34.

I merged it (and [add fix very very small bugs](https://github.com/jsakamoto/ipaddressrange/commit/d3c5acda20a17ff73c01b85467fc3c9db47c2eb7)), and published new release.

Thanks.
