### ISSUE TITLE
Signed package for v.2.1.1 and newer

### ISSUE THREAD

**Issue by PashCracken** [jsakamoto/ipaddressrange#35]
Hi,

Any chance you can create a signed package for v.2.1.1?
Would also be nice if you can automate this so that every new version will also have a new signed package

Regards,
PashCracken

**Comment by jsakamoto** [comment]
OK, I'll do it.

But, I'm sorry, I drunk too much at last night, so I maybe can't work for this issue today... 🤢 

Please give me a few days.

**Comment by jsakamoto** [comment]
I did it. 😄 

https://www.nuget.org/packages/IPAddressRange.Signed/2.2.0

Thank you for open this issue to makes me head up.

**Comment by PashCracken** [comment]
Thanks :-)
