### ISSUE TITLE
Bits static class reverses LE and GE

### ISSUE THREAD

**Issue by craigb** [jsakamoto/ipaddressrange#39]
It looks like the LE and GE operations are reversed in the Bits class.

```
[Theory]
[InlineData("0.0.0.0", "255.255.255.254")]
[InlineData("192.168.10.0", "192.168.10.254")]
[InlineData("192.168.10.0", "192.168.11.254")]
[InlineData("192.168.10.0", "192.168.11.255")]
public void Bits_comparisons_are_backwards(string start, string end)
{
    var startBytes = System.Net.IPAddress.Parse(start).GetAddressBytes();
    var endBytes = System.Net.IPAddress.Parse(end).GetAddressBytes();

    Assert.False(NetTools.Bits.LE(startBytes, endBytes));
    Assert.True(NetTools.Bits.GE(startBytes, endBytes));
}
```

**Comment by jsakamoto** [comment]
:O

**Comment by jsakamoto** [comment]
Thank you for your reporting!

Nobody could not report or recognize this problem for a long years...!

Fortunately, @Menur already fixed this problem and sent a pull request.

I should consider any programs which depend on this bug behavior, so I'll fixed this issue with keeping backward compatibility.

(In my plan, I'll add new fixed class like `Bits2`)
