### ISSUE TITLE
Incorrect results when Parse (or TryParse)

### ISSUE THREAD

**Issue by DimitriR** [jsakamoto/ipaddressrange#44]
Incorrect results and false positive responses when passing wrong IP addresses. For example:
```
IPAddressRange.TryParse("192. 168.1.0 - 192. 168.1.0", out rr);
IPAddressRange.TryParse("192.1.1 - 192.1.1", out rr);

var aa1 = IPAddressRange.Parse("192.168.1");
var aa2 = IPAddressRange.Parse("192.168.1111");
```

**Comment by jsakamoto** [comment]
Thank you for your reporting!

`192.1.1`, `192.168.1` and `192.168.1111` are all valid IPv4 address form in some platforms that include .NET Framework.

![image](https://user-images.githubusercontent.com/95908/39307240-40639546-499d-11e8-805f-8a82de040ce3.png)

See also: https://nxmnpg.lemoda.net/3/inet_aton#5

But, `192. 168.1.0` (`192.{some spaces}168.1.0`) is invalid format.

![image](https://user-images.githubusercontent.com/95908/39307284-5b4e9e5a-499d-11e8-8e49-8f1d8e674fa7.png)

I'll fix the case that including spaces pattern to treat invalid format.

**Comment by jsakamoto** [comment]
I released v.3.1.1.

https://www.nuget.org/packages/IPAddressRange/3.1.1
