### ISSUE TITLE
NetTools namespace not available

### ISSUE THREAD

**Issue by rickersilva** [jsakamoto/ipaddressrange#48]
I just installed thispackage since it was recommended in Stackoverflow. and it looks really good. 

I installed both signed version and the default. however, after installing, I can not use NetTools namespace, it says is not available. The reference is correct.

My project is a web forms app on framework 4.5.1

any suggestion on which version could I use to make it work?

**Comment by jsakamoto** [comment]
I tried to build sample web form app .net framework 4.5.1, and it just works well.

![image](https://user-images.githubusercontent.com/95908/47121096-40e8b300-d2ac-11e8-92fc-c13e369386d4.png)

The project files are here: [WebApplication2.zip](https://github.com/jsakamoto/ipaddressrange/files/2489599/WebApplication2.zip)

You should provide more and more details information of your issue, such as screen shot like I embedded one to bellow, or your project files, etc., if you want to really resolve the problem.

I can't help you with less information of your description.

**Comment by jsakamoto** [comment]
I'll close this issue since I had no reply. :(

**Comment by rickersilva** [comment]
OK. Sadly I had to. Move on other things I'll be back at this in a while.
Sure the issue is on some other reference. I still don't know and can't get
it working
