### ISSUE TITLE
3.x release notes?

### ISSUE THREAD

**Issue by memark** [jsakamoto/ipaddressrange#49]
Where can I find release notes for 3.x? Are there any breaking changes?

**Comment by manigandham** [comment]
Looks like the release notes are in the nuget spec: https://github.com/jsakamoto/ipaddressrange/blob/master/IPAddressRange/IPAddressRange.nuspec

You can read them on the nuget page: https://www.nuget.org/packages/IPAddressRange/

**Comment by memark** [comment]
@manigandham Perfect, thanks!

**Comment by memark** [comment]
For reference:

v.3.2.0
- Fix: Bits.GE/LE operations are reversed.(use GtE/LtE instead.)
- Improve: Bts.GtE/LtE methods are more faster now.
v.3.1.1 - Fix: Error if parsing IP address includes some spaces.
v.3.1.0 - Support parsing for IPv4 mapped to IPv6 address range.
v.3.0.0 - Sign the assembly. (make it to strong-named assembly.)
v.2.2.0 - Enhance: IPv4 shortcut notation support (like "192.168.0.0-255").
v.2.1.1 - Fix: Error if parsing IP address with scope id in the end.
v.2.1.0 - Enhance: Add "IsEqual" and "Decrement" methods to "Bits" utility class.
v.2.0.0 - [BREAKING CHANGE] Truncate .NET 4.0 support.
       - Enhance: can serialize/deserialize json text by JSON.NET
v.1.6.2 - Support: .NET Standard 1.4 (.NET Core) and UWP
v.1.6.1 - Fix: Add some parameter checks for throwing ArgumentNullException
v.1.6.0 - Enhance: Add "ToCidrString()" and "GetprefixLength()" method.
v.1.5.0 - Enhance: Add constructors variation / Save memory usage.
v.1.4.0 - Enhance: Add IEnumerable<IPAddress> support.
v.1.3.0 - Enhance: support both "hyphen (-)" (0x002D) and "dash (–)" (0x2013) at begin-end format.
v.1.2.1 - Fix: "Parse()" and "TryParse()" methods throw IndexOutOfRangeException when bit mask length is invalid at CIDR format.
v.1.2.0 - Enhance: Add "Parse()" and "TryParse()" methods. (Instead, the constructor which has one string argument is obsoleted.)
v.1.1.0 - Enhance: Add "Contains()" method overload version of IPAddressRange argument.
v.1.0.6 - Fix Package: Repackage with Release build. (1.0.5 was Debug build)
v.1.0.5 - Fix: IPv4 CIDR range ".../32" causes crush.
v.1.0.4 - Enhance: support bit mask range not only CIDR range.
v.1.0.3 - Fix: Can not parse the address which contains hex string.
