### ISSUE TITLE
not support "localhost"?

### ISSUE THREAD

**Issue by pedoc** [jsakamoto/ipaddressrange#50]
RT

**Comment by jsakamoto** [comment]
What did you mean?

"localhost" is a host name, not an IP address.

This library represent range of IP address, not range of host names.

If you want to resolve IP address from host name, you can do it with [Dns.GetHostAddresses(String)](https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostaddresses?view=netframework-4.7.2).

![image](https://user-images.githubusercontent.com/95908/56250522-a813e280-60ea-11e9-9bff-14f4fca87950.png)
