### ISSUE TITLE
add to nuget

### ISSUE THREAD

**Issue by dantheman213** [jsakamoto/ipaddressrange#59]
please add to nuget package manager

**Comment by jsakamoto** [comment]
Is this ↓ what you want to get?

https://www.nuget.org/packages/IPAddressRange/

**Comment by dantheman213** [comment]
Is that in the readme in master?

**Comment by jsakamoto** [comment]
I agree that is not very kind, anyway, the "nuget" badge in README is the link to nuget.org. :)

![image](https://user-images.githubusercontent.com/95908/76196041-dc295200-622c-11ea-92dd-eecab02b24ca.png)

Of course, you may can find it in search of "nuget.org" if you retry it now.

![image](https://user-images.githubusercontent.com/95908/76196232-33c7bd80-622d-11ea-896b-91df1e3f1c18.png)

Happy coding! 👍
