### ISSUE TITLE
Caclulate correct usable addresses in a range

### ISSUE THREAD

**Issue by BishoyDemian** [jsakamoto/ipaddressrange#61]
CIDR ranges /32, and /31 when given to the library to parse and then querying range.Usable, I get back a (0) where the .FirstUsable and .LastUsable properties are correctly showing a valid IP Address.

![image](https://user-images.githubusercontent.com/2049545/86998289-67bee980-c1f3-11ea-9320-e1d245dcbf0b.png)

**Comment by jsakamoto** [comment]
Hi, @BishoyDemian !

I guess, you should the issue to [here](https://github.com/lduchosal/ipnetwork/issues). :)
