### ISSUE TITLE
Extra ; that skips for loop

### ISSUE THREAD

**Issue by jscarle** [jsakamoto/ipaddressrange#70]
There's an extra ; on [line 130](https://github.com/jsakamoto/ipaddressrange/blob/e618524e76d81e44bed2e00e17bacbf8f2a376e4/IPAddressRange/Bits.cs#L130) in Bits.cs that effectively skips the for loop.

**Comment by jscarle** [comment]
Nevermind, my bad. I just realised it's intentional.

**Comment by jsakamoto** [comment]
@jscarle 
Anyway, thank you for caring about this library!
