### ISSUE TITLE
Contains not working for bigger subnet

### ISSUE THREAD

**Issue by matteogarato** [jsakamoto/ipaddressrange#82]
using the documentation:
```
// "Contains()" method also support IPAddressRange argument.
var rangeD1 = IPAddressRange.Parse("192.168.0.0/16");
var rangeD2 = IPAddressRange.Parse("192.168.10.0/24");
rangeD1.Contains(rangeD2); // is True.
```

BUT

```
// "Contains()" method also support IPAddressRange argument.
var rangeD1 = IPAddressRange.Parse("192.168.0.0/16");
var rangeD2 = IPAddressRange.Parse("192.168.1.0/24");
rangeD2.Contains(rangeD1); // is False.
```
Is it intended behavior or a bug?

**Comment by jsakamoto** [comment]
@matteogarato It is intended. Because the `rangeD2` is **overlapping** in the `rangeD1`, but the `rangeD2` doesn't **contain** the `rangeD1`.

![image](https://github.com/jsakamoto/ipaddressrange/assets/95908/767d298d-f20e-446c-9ce8-c3c4cff507d3)

Does that make sense?

**Comment by matteogarato** [comment]
yes it make sense, but logically D2 contains a part of D1 so the contains should return true in my opinion,
i propose the edit of Contains like this:
```
        public bool Contains(IPAddressRange range)
        {
            var rangeBegin = range.Begin.ToUInt32();
            var rangeEnd = range.End.ToUInt32();            
            return Begin <= rangeBegin && rangeEnd <= End || rangeBegin <= Begin && End <= rangeEnd;
        }
```
it's not a big problem, in my code now i added:
`rangeD2.Contains(rangeD1) || rangeD1.Contains(rangeD2)`
to get around the problem
