### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by SleemMostafa** [jsakamoto/ipaddressrange#83]
Use this package in many places
Is there a guarantee that the client will not be allowed to enter numbers like 888888 ?
I want it to just enter the same pattern, this is 192.168.80.0/24 or 192.168.80.0-255. without using expression pattern

**Comment by jsakamoto** [comment]
@SleemMostafa Unfortunately, this library can not be used for input validation to make user input a strict particular format. You may have to do that by yourself, such as using regular expression pattern matching.

**Comment by SleemMostafa** [comment]
ok thanks @jsakamoto
